### PR TITLE
Remove turbopack from builds

### PR DESCRIPTION
**Pull request by a3957273**

### CODE REVIEW

**Review by JR40159 — COMMENTED** [review]
Issue running the backend on Openshift- `Failed to open temporary file /etc/ssl/certs/bundleXXXXXX for ca bundle`. This then causes issues with connecting to mongo and s3

**Comment by a3957273** [comment]
That's actually an expected error.  Must have some other cause.

**Comment by ARADDCC013** [comment]
Was able to build both backend and frontend. Tested with OS, able to build model and deployement. Helm changes required in bailo.deployment.yaml, modify mounts to;
volumeMounts:
            - name: config
              mountPath: /app/config/production.cjs
              subPath: production.cjs
            - name: config
              mountPath: /app/config/custom-environment-variables.cjs
              subPath: custom-environment-variables.cjs

**Review by ARADDCC013 — APPROVED** [review]

**Comment by ARADDCC013** [comment]
helm works as expected.

**Pull request merged**
